### ISSUE TITLE
[Feat] - place on readme a description about hacktoberfest to people can contribute

### ISSUE THREAD

**Issue by J0a00liveira** [konstruktoid/datadog-package-updates#79]
idea

![hacktoberfest](https://hacktoberfest.com/_next/static/media/logo-hacktoberfest--horizontal.ebc5fdc8.svg)

# HactoberFest2023
HactoberFest2023

Hacktoberfest is an annual worldwide event held during the month of October. The event encourages open source developers to contribute to repositories through pull requests (PR).

[see more here!](https://hacktoberfest.com/)

![hacklogo](https://hacktoberfest.com/_next/static/media/logo-hacktoberfest--logomark.b91c17d2.svg)

**Comment by konstruktoid** [comment]
Hi @J0a00liveira and thanks for the idea, but I think it enough having hacktoberfest in the topics.
